version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bash -c "mvn clean install && java -jar target/myapi-0.0.1-SNAPSHOT.jar"
    ports:
      - "8080:8080"
    restart: always
    expose:
      - 8080
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/myapi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    networks:
      - backend
      - frontend
    
  mysqldb:
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapi
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    
  encoder:
    build:
      context: ./encoder
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
    networks:
      - backend
      
  mailer:
    build: ./mailer
    ports:
      - "8082:8082"
    volumes:
     - .:/mailer
    networks:
      - backend
      
  postfix:
    image: juanluisbaptiste/postfix:latest
    expose:
      - "25"
    env_file:
      - .env
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - backend

  front:
    build: ./front
    restart: always
    ports:
      - "3000:3000"
    command: "npm run start"
    depends_on:
      - api
    networks:
      - frontend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.17
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
      - frontend
      
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.17
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
      - frontend


volumes:
  mysql-data:
  esdata1:
    driver: local
  esdata2:
    driver: local
  
networks:
  backend:
  frontend:
  esnet:
